### PR TITLE
Error 411 when issuing GET request after a POST request

### PR DESCRIPTION
**Pull request by rajjanorkar**
Fixed the issue : https://github.com/omniphx/forrest/issues/197
As this is very important fix, if you can release it that would be great.

Thank you.

### CODE REVIEW

**Comment by rajjanorkar** [comment]
@omniphx could you please review and approve, as we are planning to use it in production, so if you can release new subversion that would be awesome..

Thank you.

**Comment by omniphx** [comment]
Thanks @rajjanorkar

**Comment by omniphx** [comment]
Published to version 2.5.2

**Comment by rajjanorkar** [comment]
That's so Quick @omniphx thank you so much for your help.

**Pull request merged**
