### PR TITLE
Added get getContentVersionBody and getAttachmentBody

### PR DESCRIPTION
**Pull request by danielpetrica**
Based on code provided in issue https://github.com/omniphx/forrest/issues/179
by @ShintaroNitta and @zack-carlson

### CODE REVIEW

**Comment by danielpetrica** [comment]
Drafted as I need to integrate facade and the readme file

**Comment by danielpetrica** [comment]
I tested it with the client credential workflow only

**Comment by danielpetrica** [comment]
Hi I'm using the eloquent package and this library in a site we're developing at work. 
I found out that we need this code to be able to download files uploaded to sales force with the contentVersion flow. 
I managed to upload the file but I incurred the same error as in ticket https://github.com/omniphx/forrest/issues/179. Instead of overwriting the class, I think it is more elegant to extend the base class so we can use the method in all authentication classes.

**Comment by omniphx** [comment]
Hi @danielpetrica, thanks for the contribution. I'll go and merge this in since it shouldn't be a breaking change for the Web Auth flow.

**Comment by danielpetrica** [comment]
Thank you for the merge and for the packet. It's making my job eaier ❤️

**Pull request merged**
