### PR TITLE
Update readme on UserPassword usage

### PR DESCRIPTION
**Pull request by rtconner**

### CODE REVIEW

**Comment by omniphx** [comment]
Appreciate your contribution, but this part of the documentation is just to reveal the routes included in the package. Here's the file: https://github.com/omniphx/forrest/blob/master/src/Omniphx/Forrest/Providers/Laravel/Routes/UserPassword.php

Let me know if you think it's unclear.

**Comment by rtconner** [comment]
I don't understand why routes have to be involved at all. I call Forrest::authenticate() and the token gets put into the session then I can make other calls. Routes never get touched or used, and are not needed.

**Comment by rtconner** [comment]
```php
\Forrest::authenticate();
\Forrest::versions();
```

**Comment by omniphx** [comment]
On it's own, the UserName password flow doesn't need routes, but the routes are necessary for allowing compatibility between Web Server and the Username Password flows.

Take for example, you create an App that uses the Web Server authentication. You want to test that the app is working, but you don't want to waste time re-authenticating. Simply changing the configuration to "User Password" will allow you test the app without breaking it.

If you don't like the routes, you can simply override them.

**Comment by rtconner** [comment]
Yeah, that is why I edited the docs. The docs weren't clear that you don't need to use routes at all.

**Comment by rtconner** [comment]
This implements feature request #25

**Comment by omniphx** [comment]
Good stuff. I didn't quite understand what you initially meant by changing the instance URL. Thought you just wanted to change the login URL. Makes more sense now.

Also, decided to modify your changes to the documentation. I'm not that proficient with git, so I'll merge my changes after your pull request has been merged.

**Comment by rtconner** [comment]
Ok thank you. I have other small ideas but this was the one was the biggest change I was hoping you would accept.

**Pull request merged**
