### PR TITLE
add Laravel 10 support

### PR DESCRIPTION
**Pull request by jonnott**
Laravel 10 launching today (14th Feb)

### CODE REVIEW

**Comment by jonnott** [comment]
@omniphx

**Comment by omniphx** [comment]
Thanks! @jonnott

**Comment by jonnott** [comment]
No probs @omniphx .. is it possible to tag a new release?

**Comment by omniphx** [comment]
@jonnott yup, tagged it right after I merged: https://github.com/omniphx/forrest/releases/tag/v2.15.0

**Pull request merged**
