### PR TITLE
Add methods to Forrest corresponding to standard REST Methods

### PR DESCRIPTION
**Pull request by rtconner**
I felt like I needed lower level ability to hand craft rest calls.

### CODE REVIEW

**Comment by omniphx** [comment]
I'm bit reluctant about this, because it's adding extra complexity to the codebase. However, I do see the need for experimenting. The only issue I find is that the endpoint in the GET method hardcoded (`/services/data/v31.0/`). I'll merge it once that's fixed.

**Comment by rtconner** [comment]
It is fixed :) --> https://github.com/rtconner/forrest/commit/9a8a520b374e4d61529fc281912fcb2b052abbed

**Comment by rtconner** [comment]
Honestly .. this feature is what I thought Id' find when looking for a SF REST client. Was a bit surprised that it wasn't out there. I think it the most basic piece to use when wanted.

**Comment by omniphx** [comment]
:+1:

That's a good point. I guess I thought the package was still flexible enough without it, but I guess you never know when you need to use some basic requests. Also, really appreciate your contributions. Hope it doesn't seem like I'm trying to fight you on some of these smaller issues. :)

On a side note, I really need to create a development branch for some of these new features. For now, this merge will be available with the `dev-master` version. I have a few more changes I need to make before rolling out the next version.

**Pull request merged**
