### PR TITLE
More useful error reporting on exception

### PR DESCRIPTION
**Pull request by rtconner**
getMessage outputs info more useful to the developer

### CODE REVIEW

**Comment by rtconner** [comment]
Ack, don't merge, I'll figure out the failure on the test and re-request

**Comment by omniphx** [comment]
Hm... think you could provide an example? I find the response from Salesforce to be more helpful. 

For example, this is what I get if I try to update a record with a false Salesforce Id.

With getMessage(), I get:
```
Salesforce response error: Client error response [url] https://na17.salesforce.com/services/data/v32.0/sobjects/Account/001i000000xxxxxx [status code] 404 [reason phrase] Not Found 
```

With getResponse(), I get:
```
Salesforce response error: HTTP/1.1 404 Not Found Date: Thu, 08 Jan 2015 22:24:59 GMT Set-Cookie: BrowserId=oaWctnzJR6K1w0DdKJvVPQ;Path=/;Domain=.salesforce.com;Expires=Mon, 09-Mar-2015 22:24:59 GMT Expires: Thu, 01 Jan 1970 00:00:00 GMT Sforce-Limit-Info: api-usage=4/15000 Content-Type: application/json;charset=UTF-8 Transfer-Encoding: chunked [{"errorCode":"NOT_FOUND","message":"Provided external ID field does not exist or is not accessible: 001i000000xxxxxx"}] 
```
I find the response message to be more explicit.

**Comment by rtconner** [comment]
Hrm. Bottom one is missing the URL requested. Maybe we need to mix and match them?

**Comment by omniphx** [comment]
Mix/match is not a bad idea.

Changing it to `$e->getResponse()->json()[0]['message']` would get rid of the header:
```
Salesforce response error: Provided external ID field does not exist or is not accessible: 001i000000xxxxxx
```
...but would not work for anyone using an XML format.

`$e->getResponse()->getBody()` is another option. Any ideas?

**Pull request closed without merging**
