### PR TITLE
also support Laravel 8.x illuminate components

### PR DESCRIPTION
**Pull request by jonnott**
Support for Laravel 8.x

### CODE REVIEW

**Comment by jonnott** [comment]
@omniphx

**Comment by jonnott** [comment]
@yankewei

**Comment by jonnott** [comment]
@omniphx Can this be merged and released soon? It's the only thing preventing me upgrading a project to Laravel 8..

**Comment by omniphx** [comment]
All set, I'm going to do some testing before versioning but should be available in dev-master

**Comment by jonnott** [comment]
> All set, I'm going to do some testing before versioning but should be available in dev-master

Awesome. Thanks!

**Comment by jonnott** [comment]
@omniphx Working ok for me as dev-master for now.

**Comment by jonnott** [comment]
Are we any closer to a release being tagged? @omniphx

**Comment by omniphx** [comment]
@jonnott Version 2.9

**Comment by jonnott** [comment]
Wow, like magic, a version comes out! Cool..

**Pull request merged**
